services:
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    user: "1001:1001"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aimolt
      POSTGRES_DB: aimolt
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/postgresql/data
